s = 'Prótons e nêutrons'

print('---------------')
print(s[5:])
print(s[5:12])
print(s[:4])
print(s[-1])
print(s[:-1])
print(s[::2])
print(s[::-1])
print(s * 2)
print(s.upper())
print(s.lower())
print(s.split(' '))
print(s.capitalize())
print(s.count('a'))
print(s.isalnum())
print(s.islower())
print(s.isspace())
print(s.endswith('y'))
print('---------------')